name: Deploy Locaweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "public"
          remoteDir: "public_html"
